# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audit.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "audit_message" do
    oneof :msg do
      optional :commit, :message, 1, "commit_notification"
      optional :leader_status, :message, 2, "leader_status"
    end
  end
  add_message "leader_status" do
    optional :term, :uint64, 1
    optional :leader, :string, 2
    optional :current_log_index, :uint64, 3
    optional :current_commit_index, :uint64, 4
  end
  add_message "commit_notification" do
    optional :sender_uuid, :string, 1
    optional :log_index, :uint64, 2
    optional :operation, :string, 3
  end
end

Audit_message = Google::Protobuf::DescriptorPool.generated_pool.lookup("audit_message").msgclass
Leader_status = Google::Protobuf::DescriptorPool.generated_pool.lookup("leader_status").msgclass
Commit_notification = Google::Protobuf::DescriptorPool.generated_pool.lookup("commit_notification").msgclass
