# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "database_msg" do
    optional :header, :message, 2, "database_header"
    oneof :msg do
      optional :create, :message, 10, "database_create"
      optional :read, :message, 11, "database_read"
      optional :update, :message, 12, "database_update"
      optional :delete, :message, 13, "database_delete"
      optional :has, :message, 14, "database_has"
      optional :keys, :message, 15, "database_empty"
      optional :size, :message, 16, "database_empty"
    end
  end
  add_message "database_redirect_response" do
    optional :leader_id, :string, 1
    optional :leader_name, :string, 2
    optional :leader_host, :string, 3
    optional :leader_port, :uint32, 4
    optional :leader_http_port, :uint32, 5
  end
  add_message "database_header" do
    optional :db_uuid, :string, 1
    optional :transaction_id, :uint64, 2
  end
  add_message "database_create" do
    optional :key, :string, 2
    optional :value, :bytes, 3
  end
  add_message "database_read" do
    optional :key, :string, 2
  end
  add_message "database_update" do
    optional :key, :string, 2
    optional :value, :bytes, 3
  end
  add_message "database_delete" do
    optional :key, :string, 2
  end
  add_message "database_has" do
    optional :key, :string, 2
  end
  add_message "database_empty" do
  end
  add_message "database_response" do
    optional :header, :message, 1, "database_header"
    oneof :success do
      optional :redirect, :message, 2, "database_redirect_response"
      optional :resp, :message, 3, "database_response.response"
    end
  end
  add_message "database_response.response" do
    optional :value, :bytes, 4
    optional :has, :bool, 5
    optional :size, :int32, 6
    optional :error, :string, 7
    repeated :keys, :string, 8
  end
end

Database_msg = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_msg").msgclass
Database_redirect_response = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_redirect_response").msgclass
Database_header = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_header").msgclass
Database_create = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_create").msgclass
Database_read = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_read").msgclass
Database_update = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_update").msgclass
Database_delete = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_delete").msgclass
Database_has = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_has").msgclass
Database_empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_empty").msgclass
Database_response = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_response").msgclass
Database_response::Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("database_response.response").msgclass
